eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true
okta:
  oauth2:
    issuer: https://dev-zrsfgnro1e3y22fh.us.auth0.com/
    audience: https://microservicestestapi
